const DEFAULT_MODEL = "gemini-2.0-flash";
const LATEST_ANALYSIS_KEY = "latestAnalysis";
const SETTINGS_DEFAULTS = {
  apiKey: "",
  model: DEFAULT_MODEL,
  autoScan: true
};

const AI_MARKERS = [
  "in conclusion",
  "delve",
  "ever-evolving",
  "unlock",
  "game-changing",
  "revolutionary",
  "leverage",
  "transformative",
  "furthermore",
  "moreover",
  "additionally",
  "seamless",
  "elevate",
  "streamline",
  "as an ai",
  "generated by ai"
];

function clamp(value, minimum, maximum) {
  return Math.max(minimum, Math.min(maximum, value));
}

function getStorageArea(areaName) {
  if (typeof chrome === "undefined" || !chrome.storage?.[areaName]) {
    return null;
  }

  return chrome.storage[areaName];
}

function storageGet(areaName, keys) {
  const area = getStorageArea(areaName);
  if (!area) {
    return Promise.resolve({});
  }

  return new Promise((resolve) => area.get(keys, resolve));
}

function storageSet(areaName, values) {
  const area = getStorageArea(areaName);
  if (!area) {
    return Promise.resolve();
  }

  return new Promise((resolve) => area.set(values, resolve));
}

async function getSettings() {
  const settings = await storageGet("sync", Object.keys(SETTINGS_DEFAULTS));
  return { ...SETTINGS_DEFAULTS, ...settings };
}

async function storeLatestAnalysis(result) {
  await storageSet("local", {
    [LATEST_ANALYSIS_KEY]: {
      ...result,
      storedAt: new Date().toISOString()
    }
  });
}

function unique(values) {
  return [...new Set(values.filter(Boolean))];
}

function splitSentences(text) {
  return text
    .split(/(?<=[.!?])\s+/)
    .map((sentence) => sentence.trim())
    .filter(Boolean);
}

function getRepeatedSentenceRatio(text) {
  const sentences = splitSentences(text.toLowerCase());
  if (sentences.length < 3) {
    return 0;
  }

  const seen = new Set();
  let repeated = 0;

  for (const sentence of sentences) {
    if (seen.has(sentence)) {
      repeated += 1;
    }
    seen.add(sentence);
  }

  return repeated / sentences.length;
}

function topMarkerHits(text) {
  const lower = text.toLowerCase();
  return AI_MARKERS.map((marker) => ({
    marker,
    count: lower.split(marker).length - 1
  }))
    .filter((entry) => entry.count > 0)
    .sort((left, right) => right.count - left.count);
}

function heuristicAnalysis(payload) {
  const text = `${payload.title || ""}\n${payload.text || ""}`.trim();
  const markers = topMarkerHits(text);
  const repeatedSentenceRatio = getRepeatedSentenceRatio(text);
  const linkCount = Array.isArray(payload.links) ? payload.links.length : 0;
  const candidateCount = Array.isArray(payload.candidates) ? payload.candidates.length : 0;

  let score = 12;
  score += markers.reduce((total, marker) => total + Math.min(marker.count, 3) * 10, 0);
  score += Math.round(repeatedSentenceRatio * 35);
  score += Math.min(linkCount, 8);
  score += Math.min(candidateCount, 10);

  const dominantMarkers = markers.slice(0, 4).map((entry) => entry.marker);
  const verdict =
    score >= 75
      ? "Severe synthetic saturation"
      : score >= 45
        ? "Likely machine-assisted"
        : "Mostly human, but not clean";

  const explanation =
    dominantMarkers.length > 0
      ? `Arcadia spotted inflated phrasing such as ${dominantMarkers
          .map((marker) => `"${marker}"`)
          .join(", ")} plus repeated sentence patterns.`
      : "Arcadia found a lighter signal, but the page still shows polished repetition and scalable filler patterns.";

  return normalizeAnalysis({
    source: "heuristic",
    model: "local-heuristic",
    score,
    verdict,
    explanation,
    badUse:
      "When synthetic copy floods a page, voice gets flattened, accountability gets washed out, and trust is replaced by frictionless sludge.",
    highlights: dominantMarkers,
    url: payload.url,
    title: payload.title,
    analysedAt: new Date().toISOString()
  });
}

function extractJson(text) {
  const trimmed = (text || "").trim();
  if (!trimmed) {
    return null;
  }

  const fenced = trimmed.match(/```(?:json)?\s*([\s\S]*?)```/i);
  const candidate = fenced ? fenced[1] : trimmed;
  const firstBrace = candidate.indexOf("{");
  const lastBrace = candidate.lastIndexOf("}");

  if (firstBrace === -1 || lastBrace === -1 || lastBrace <= firstBrace) {
    return null;
  }

  try {
    return JSON.parse(candidate.slice(firstBrace, lastBrace + 1));
  } catch (error) {
    return null;
  }
}

function normalizeAnalysis(raw) {
  const score = clamp(Number(raw?.score) || 0, 0, 100);

  return {
    score,
    verdict: raw?.verdict || "Unknown signal",
    explanation:
      raw?.explanation ||
      "Arcadia could not produce a clear explanation, so treat this result as directional rather than final.",
    badUse:
      raw?.badUse ||
      "Synthetic publishing at scale launders intent, compresses nuance, and makes low-accountability content easier to spread.",
    highlights: unique((raw?.highlights || []).map((value) => String(value).trim())).slice(0, 8),
    source: raw?.source || "gemini",
    model: raw?.model || DEFAULT_MODEL,
    url: raw?.url || "",
    title: raw?.title || "",
    analysedAt: raw?.analysedAt || new Date().toISOString()
  };
}

async function analyzeWithGemini(payload, apiKey, model) {
  const prompt = [
    "You are Arcadia, a brutal, critical AI-content detector.",
    "Inspect the supplied page content and respond with JSON only.",
    "Return an object with keys: score, verdict, explanation, badUse, highlights.",
    "score must be an integer from 0 to 100 describing how much of the visible content appears AI-generated.",
    "explanation must be direct and critical.",
    "badUse must explain why the detected synthetic usage is harmful.",
    "highlights must be an array of short suspicious phrases that appear in the page."
  ].join(" ");

  const response = await fetch(
    `https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent?key=${encodeURIComponent(apiKey)}`,
    {
      method: "POST",
      headers: {
        "Content-Type": "application/json"
      },
      body: JSON.stringify({
        contents: [
          {
            role: "user",
            parts: [
              {
                text: `${prompt}\n\nPage payload:\n${JSON.stringify(payload)}`
              }
            ]
          }
        ],
        generationConfig: {
          temperature: 0.2,
          responseMimeType: "application/json"
        }
      })
    }
  );

  if (!response.ok) {
    const failureText = await response.text();
    throw new Error(`Gemini request failed (${response.status}): ${failureText}`);
  }

  const data = await response.json();
  const modelText = data?.candidates?.[0]?.content?.parts?.map((part) => part.text || "").join("\n") || "";
  const parsed = extractJson(modelText);

  if (!parsed) {
    throw new Error("Gemini response did not contain valid JSON.");
  }

  return normalizeAnalysis({
    ...parsed,
    source: "gemini",
    model,
    url: payload.url,
    title: payload.title,
    analysedAt: new Date().toISOString()
  });
}

async function runAnalysis(payload) {
  const settings = await getSettings();

  if (!settings.apiKey) {
    return heuristicAnalysis(payload);
  }

  try {
    return await analyzeWithGemini(payload, settings.apiKey, settings.model || DEFAULT_MODEL);
  } catch (error) {
    const fallback = heuristicAnalysis(payload);
    return {
      ...fallback,
      source: "heuristic-fallback",
      explanation: `${fallback.explanation} Gemini failed, so Arcadia dropped back to the local detector.`,
      geminiError: String(error.message || error)
    };
  }
}

if (typeof chrome !== "undefined" && chrome.runtime?.onMessage) {
  chrome.runtime.onMessage.addListener((message, sender, sendResponse) => {
    if (message?.type === "analyze-page") {
      runAnalysis(message.payload || {})
        .then(async (analysis) => {
          await storeLatestAnalysis(analysis);
          sendResponse({ ok: true, result: analysis });
        })
        .catch((error) => {
          sendResponse({ ok: false, error: String(error.message || error) });
        });
      return true;
    }

    if (message?.type === "get-latest-analysis") {
      storageGet("local", [LATEST_ANALYSIS_KEY]).then((stored) => {
        sendResponse({ ok: true, result: stored[LATEST_ANALYSIS_KEY] || null });
      });
      return true;
    }

    return false;
  });
}

if (typeof module !== "undefined") {
  module.exports = {
    heuristicAnalysis,
    normalizeAnalysis,
    extractJson,
    topMarkerHits,
    getRepeatedSentenceRatio
  };
}
